


select * from nodetab;
INSERT INTO nodetab (description, status) VALUES ('Test Description', 'Pending');


CREATE TABLE nodetab_new (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR2(255),
    status VARCHAR2(50),
    PRIMARY KEY (id)
);
